/*
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWorkflowScopeProvider extends DelegatingScopeProvider {
}
