/**
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl.workflow;

import com.netfective.workflow.Wfl.CartridgeWFL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cartridge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link com.netfective.editor.dsl.workflow.Cartridge#getCartridge <em>Cartridge</em>}</li>
 *   <li>{@link com.netfective.editor.dsl.workflow.Cartridge#getActivated <em>Activated</em>}</li>
 * </ul>
 * </p>
 *
 * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getCartridge()
 * @model
 * @generated
 */
public interface Cartridge extends EObject
{
  /**
   * Returns the value of the '<em><b>Cartridge</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cartridge</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartridge</em>' reference.
   * @see #setCartridge(CartridgeWFL)
   * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getCartridge_Cartridge()
   * @model
   * @generated
   */
  CartridgeWFL getCartridge();

  /**
   * Sets the value of the '{@link com.netfective.editor.dsl.workflow.Cartridge#getCartridge <em>Cartridge</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartridge</em>' reference.
   * @see #getCartridge()
   * @generated
   */
  void setCartridge(CartridgeWFL value);

  /**
   * Returns the value of the '<em><b>Activated</b></em>' attribute.
   * The literals are from the enumeration {@link com.netfective.editor.dsl.workflow.Activated}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Activated</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activated</em>' attribute.
   * @see com.netfective.editor.dsl.workflow.Activated
   * @see #setActivated(Activated)
   * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getCartridge_Activated()
   * @model
   * @generated
   */
  Activated getActivated();

  /**
   * Sets the value of the '{@link com.netfective.editor.dsl.workflow.Cartridge#getActivated <em>Activated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activated</em>' attribute.
   * @see com.netfective.editor.dsl.workflow.Activated
   * @see #getActivated()
   * @generated
   */
  void setActivated(Activated value);

} // Cartridge
