/**
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl.workflow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link com.netfective.editor.dsl.workflow.Model#getWFBsp <em>WF Bsp</em>}</li>
 *   <li>{@link com.netfective.editor.dsl.workflow.Model#getWFProperty <em>WF Property</em>}</li>
 *   <li>{@link com.netfective.editor.dsl.workflow.Model#getWFResource <em>WF Resource</em>}</li>
 * </ul>
 * </p>
 *
 * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>WF Bsp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>WF Bsp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>WF Bsp</em>' containment reference.
   * @see #setWFBsp(Cartridges)
   * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getModel_WFBsp()
   * @model containment="true"
   * @generated
   */
  Cartridges getWFBsp();

  /**
   * Sets the value of the '{@link com.netfective.editor.dsl.workflow.Model#getWFBsp <em>WF Bsp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WF Bsp</em>' containment reference.
   * @see #getWFBsp()
   * @generated
   */
  void setWFBsp(Cartridges value);

  /**
   * Returns the value of the '<em><b>WF Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>WF Property</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>WF Property</em>' containment reference.
   * @see #setWFProperty(Properties)
   * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getModel_WFProperty()
   * @model containment="true"
   * @generated
   */
  Properties getWFProperty();

  /**
   * Sets the value of the '{@link com.netfective.editor.dsl.workflow.Model#getWFProperty <em>WF Property</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WF Property</em>' containment reference.
   * @see #getWFProperty()
   * @generated
   */
  void setWFProperty(Properties value);

  /**
   * Returns the value of the '<em><b>WF Resource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>WF Resource</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>WF Resource</em>' containment reference.
   * @see #setWFResource(Resources)
   * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getModel_WFResource()
   * @model containment="true"
   * @generated
   */
  Resources getWFResource();

  /**
   * Sets the value of the '{@link com.netfective.editor.dsl.workflow.Model#getWFResource <em>WF Resource</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WF Resource</em>' containment reference.
   * @see #getWFResource()
   * @generated
   */
  void setWFResource(Resources value);

} // Model
