/**
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl.workflow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Cartridge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link com.netfective.editor.dsl.workflow.PropertyCartridge#getCartridge <em>Cartridge</em>}</li>
 *   <li>{@link com.netfective.editor.dsl.workflow.PropertyCartridge#getProperties <em>Properties</em>}</li>
 * </ul>
 * </p>
 *
 * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getPropertyCartridge()
 * @model
 * @generated
 */
public interface PropertyCartridge extends EObject
{
  /**
   * Returns the value of the '<em><b>Cartridge</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cartridge</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartridge</em>' reference.
   * @see #setCartridge(Cartridge)
   * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getPropertyCartridge_Cartridge()
   * @model
   * @generated
   */
  Cartridge getCartridge();

  /**
   * Sets the value of the '{@link com.netfective.editor.dsl.workflow.PropertyCartridge#getCartridge <em>Cartridge</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartridge</em>' reference.
   * @see #getCartridge()
   * @generated
   */
  void setCartridge(Cartridge value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.netfective.editor.dsl.workflow.Property}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Properties</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.netfective.editor.dsl.workflow.WorkflowPackage#getPropertyCartridge_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

} // PropertyCartridge
