/**
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl.workflow;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.netfective.editor.dsl.workflow.WorkflowFactory
 * @model kind="package"
 * @generated
 */
public interface WorkflowPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "workflow";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.netfective.com/editor/dsl/Workflow";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "workflow";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WorkflowPackage eINSTANCE = com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl.init();

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.ModelImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>WF Bsp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WF_BSP = 0;

  /**
   * The feature id for the '<em><b>WF Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WF_PROPERTY = 1;

  /**
   * The feature id for the '<em><b>WF Resource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WF_RESOURCE = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.CartridgesImpl <em>Cartridges</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.CartridgesImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getCartridges()
   * @generated
   */
  int CARTRIDGES = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTRIDGES__NAME = 0;

  /**
   * The feature id for the '<em><b>Cartdriges</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTRIDGES__CARTDRIGES = 1;

  /**
   * The number of structural features of the '<em>Cartridges</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTRIDGES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.PropertiesImpl <em>Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.PropertiesImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getProperties()
   * @generated
   */
  int PROPERTIES = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES__NAME = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.ResourcesImpl <em>Resources</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.ResourcesImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getResources()
   * @generated
   */
  int RESOURCES = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCES__NAME = 0;

  /**
   * The feature id for the '<em><b>Resources</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCES__RESOURCES = 1;

  /**
   * The number of structural features of the '<em>Resources</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.ResourceImpl <em>Resource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.ResourceImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getResource()
   * @generated
   */
  int RESOURCE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Resource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.PropertyCartridgeImpl <em>Property Cartridge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.PropertyCartridgeImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getPropertyCartridge()
   * @generated
   */
  int PROPERTY_CARTRIDGE = 5;

  /**
   * The feature id for the '<em><b>Cartridge</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CARTRIDGE__CARTRIDGE = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CARTRIDGE__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Property Cartridge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_CARTRIDGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.PropertyImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 0;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.impl.CartridgeImpl <em>Cartridge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.impl.CartridgeImpl
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getCartridge()
   * @generated
   */
  int CARTRIDGE = 7;

  /**
   * The feature id for the '<em><b>Cartridge</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTRIDGE__CARTRIDGE = 0;

  /**
   * The feature id for the '<em><b>Activated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTRIDGE__ACTIVATED = 1;

  /**
   * The number of structural features of the '<em>Cartridge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTRIDGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.netfective.editor.dsl.workflow.Activated <em>Activated</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.netfective.editor.dsl.workflow.Activated
   * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getActivated()
   * @generated
   */
  int ACTIVATED = 8;


  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.netfective.editor.dsl.workflow.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link com.netfective.editor.dsl.workflow.Model#getWFBsp <em>WF Bsp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>WF Bsp</em>'.
   * @see com.netfective.editor.dsl.workflow.Model#getWFBsp()
   * @see #getModel()
   * @generated
   */
  EReference getModel_WFBsp();

  /**
   * Returns the meta object for the containment reference '{@link com.netfective.editor.dsl.workflow.Model#getWFProperty <em>WF Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>WF Property</em>'.
   * @see com.netfective.editor.dsl.workflow.Model#getWFProperty()
   * @see #getModel()
   * @generated
   */
  EReference getModel_WFProperty();

  /**
   * Returns the meta object for the containment reference '{@link com.netfective.editor.dsl.workflow.Model#getWFResource <em>WF Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>WF Resource</em>'.
   * @see com.netfective.editor.dsl.workflow.Model#getWFResource()
   * @see #getModel()
   * @generated
   */
  EReference getModel_WFResource();

  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.Cartridges <em>Cartridges</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cartridges</em>'.
   * @see com.netfective.editor.dsl.workflow.Cartridges
   * @generated
   */
  EClass getCartridges();

  /**
   * Returns the meta object for the attribute '{@link com.netfective.editor.dsl.workflow.Cartridges#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netfective.editor.dsl.workflow.Cartridges#getName()
   * @see #getCartridges()
   * @generated
   */
  EAttribute getCartridges_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.netfective.editor.dsl.workflow.Cartridges#getCartdriges <em>Cartdriges</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cartdriges</em>'.
   * @see com.netfective.editor.dsl.workflow.Cartridges#getCartdriges()
   * @see #getCartridges()
   * @generated
   */
  EReference getCartridges_Cartdriges();

  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.Properties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Properties</em>'.
   * @see com.netfective.editor.dsl.workflow.Properties
   * @generated
   */
  EClass getProperties();

  /**
   * Returns the meta object for the attribute '{@link com.netfective.editor.dsl.workflow.Properties#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netfective.editor.dsl.workflow.Properties#getName()
   * @see #getProperties()
   * @generated
   */
  EAttribute getProperties_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.netfective.editor.dsl.workflow.Properties#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see com.netfective.editor.dsl.workflow.Properties#getProperties()
   * @see #getProperties()
   * @generated
   */
  EReference getProperties_Properties();

  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.Resources <em>Resources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resources</em>'.
   * @see com.netfective.editor.dsl.workflow.Resources
   * @generated
   */
  EClass getResources();

  /**
   * Returns the meta object for the attribute '{@link com.netfective.editor.dsl.workflow.Resources#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netfective.editor.dsl.workflow.Resources#getName()
   * @see #getResources()
   * @generated
   */
  EAttribute getResources_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.netfective.editor.dsl.workflow.Resources#getResources <em>Resources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Resources</em>'.
   * @see com.netfective.editor.dsl.workflow.Resources#getResources()
   * @see #getResources()
   * @generated
   */
  EReference getResources_Resources();

  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.Resource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resource</em>'.
   * @see com.netfective.editor.dsl.workflow.Resource
   * @generated
   */
  EClass getResource();

  /**
   * Returns the meta object for the attribute '{@link com.netfective.editor.dsl.workflow.Resource#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netfective.editor.dsl.workflow.Resource#getName()
   * @see #getResource()
   * @generated
   */
  EAttribute getResource_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.netfective.editor.dsl.workflow.Resource#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see com.netfective.editor.dsl.workflow.Resource#getProperties()
   * @see #getResource()
   * @generated
   */
  EReference getResource_Properties();

  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.PropertyCartridge <em>Property Cartridge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Cartridge</em>'.
   * @see com.netfective.editor.dsl.workflow.PropertyCartridge
   * @generated
   */
  EClass getPropertyCartridge();

  /**
   * Returns the meta object for the reference '{@link com.netfective.editor.dsl.workflow.PropertyCartridge#getCartridge <em>Cartridge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cartridge</em>'.
   * @see com.netfective.editor.dsl.workflow.PropertyCartridge#getCartridge()
   * @see #getPropertyCartridge()
   * @generated
   */
  EReference getPropertyCartridge_Cartridge();

  /**
   * Returns the meta object for the containment reference list '{@link com.netfective.editor.dsl.workflow.PropertyCartridge#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see com.netfective.editor.dsl.workflow.PropertyCartridge#getProperties()
   * @see #getPropertyCartridge()
   * @generated
   */
  EReference getPropertyCartridge_Properties();

  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see com.netfective.editor.dsl.workflow.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link com.netfective.editor.dsl.workflow.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.netfective.editor.dsl.workflow.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for class '{@link com.netfective.editor.dsl.workflow.Cartridge <em>Cartridge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cartridge</em>'.
   * @see com.netfective.editor.dsl.workflow.Cartridge
   * @generated
   */
  EClass getCartridge();

  /**
   * Returns the meta object for the reference '{@link com.netfective.editor.dsl.workflow.Cartridge#getCartridge <em>Cartridge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cartridge</em>'.
   * @see com.netfective.editor.dsl.workflow.Cartridge#getCartridge()
   * @see #getCartridge()
   * @generated
   */
  EReference getCartridge_Cartridge();

  /**
   * Returns the meta object for the attribute '{@link com.netfective.editor.dsl.workflow.Cartridge#getActivated <em>Activated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Activated</em>'.
   * @see com.netfective.editor.dsl.workflow.Cartridge#getActivated()
   * @see #getCartridge()
   * @generated
   */
  EAttribute getCartridge_Activated();

  /**
   * Returns the meta object for enum '{@link com.netfective.editor.dsl.workflow.Activated <em>Activated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Activated</em>'.
   * @see com.netfective.editor.dsl.workflow.Activated
   * @generated
   */
  EEnum getActivated();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WorkflowFactory getWorkflowFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.ModelImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>WF Bsp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__WF_BSP = eINSTANCE.getModel_WFBsp();

    /**
     * The meta object literal for the '<em><b>WF Property</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__WF_PROPERTY = eINSTANCE.getModel_WFProperty();

    /**
     * The meta object literal for the '<em><b>WF Resource</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__WF_RESOURCE = eINSTANCE.getModel_WFResource();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.CartridgesImpl <em>Cartridges</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.CartridgesImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getCartridges()
     * @generated
     */
    EClass CARTRIDGES = eINSTANCE.getCartridges();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTRIDGES__NAME = eINSTANCE.getCartridges_Name();

    /**
     * The meta object literal for the '<em><b>Cartdriges</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARTRIDGES__CARTDRIGES = eINSTANCE.getCartridges_Cartdriges();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.PropertiesImpl <em>Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.PropertiesImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getProperties()
     * @generated
     */
    EClass PROPERTIES = eINSTANCE.getProperties();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTIES__NAME = eINSTANCE.getProperties_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTIES__PROPERTIES = eINSTANCE.getProperties_Properties();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.ResourcesImpl <em>Resources</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.ResourcesImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getResources()
     * @generated
     */
    EClass RESOURCES = eINSTANCE.getResources();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESOURCES__NAME = eINSTANCE.getResources_Name();

    /**
     * The meta object literal for the '<em><b>Resources</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESOURCES__RESOURCES = eINSTANCE.getResources_Resources();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.ResourceImpl <em>Resource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.ResourceImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getResource()
     * @generated
     */
    EClass RESOURCE = eINSTANCE.getResource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESOURCE__NAME = eINSTANCE.getResource_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESOURCE__PROPERTIES = eINSTANCE.getResource_Properties();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.PropertyCartridgeImpl <em>Property Cartridge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.PropertyCartridgeImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getPropertyCartridge()
     * @generated
     */
    EClass PROPERTY_CARTRIDGE = eINSTANCE.getPropertyCartridge();

    /**
     * The meta object literal for the '<em><b>Cartridge</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_CARTRIDGE__CARTRIDGE = eINSTANCE.getPropertyCartridge_Cartridge();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_CARTRIDGE__PROPERTIES = eINSTANCE.getPropertyCartridge_Properties();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.PropertyImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.impl.CartridgeImpl <em>Cartridge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.impl.CartridgeImpl
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getCartridge()
     * @generated
     */
    EClass CARTRIDGE = eINSTANCE.getCartridge();

    /**
     * The meta object literal for the '<em><b>Cartridge</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARTRIDGE__CARTRIDGE = eINSTANCE.getCartridge_Cartridge();

    /**
     * The meta object literal for the '<em><b>Activated</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTRIDGE__ACTIVATED = eINSTANCE.getCartridge_Activated();

    /**
     * The meta object literal for the '{@link com.netfective.editor.dsl.workflow.Activated <em>Activated</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.netfective.editor.dsl.workflow.Activated
     * @see com.netfective.editor.dsl.workflow.impl.WorkflowPackageImpl#getActivated()
     * @generated
     */
    EEnum ACTIVATED = eINSTANCE.getActivated();

  }

} //WorkflowPackage
