/*
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractWorkflowValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.netfective.editor.dsl.workflow.WorkflowPackage.eINSTANCE);
		return result;
	}
	
}
