/*
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WorkflowAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/netfective/editor/dsl/parser/antlr/internal/InternalWorkflow.tokens");
	}
}
