/*
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WorkflowStandaloneSetup extends WorkflowStandaloneSetupGenerated {

	def static void doSetup() {
		new WorkflowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
