/*
 * generated by Xtext 2.9.1
 */
package com.netfective.editor.dsl

import com.netfective.editor.dsl.nameprovider.WorkflowNameProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WorkflowRuntimeModule extends AbstractWorkflowRuntimeModule {
	override bindIQualifiedNameProvider() {
		return WorkflowNameProvider;
	}
}
